# Usa la imagen base oficial de PostgreSQL desde Docker Hub
FROM postgres:latest
# Variables de entorno para la configuración de PostgreSQL
ENV POSTGRES_DB=bankservices
ENV POSTGRES_USER=adminbankservices
ENV POSTGRES_PASSWORD=Admin123

# Copia un script SQL de inicialización a la imagen
VOLUME /var/lib/postgresql/data
